version: 0.2

phases:
  install:
    commands:
      - echo Updating dependencies...
      - printenv
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm run test
  post_build:
    commands:
      - echo Building deploy artifacts...
      - mkdir -p build
      - tar -jcf gdax-trader.tar.bz2 *

artifacts:
  files:
    - build*/**
  discard-paths: yes